hospitals = ["Changi General Hospital (CGH)",
             "Gleneagles Hospital",
             "Khoo Teck Puat Hospital",
             "Mount Alvernia Hospital",
             "National University Hospital (NUH)",
             "Ng Teng Fong General Hospital & Jurong Community Hospital",
             "Parkway East Hospital (former East Shore Hospital)",
             "Raffles Hospital",
             "Sengkang General Hospital",
             "Singapore General Hospital (SGH)",
             "Tan Tock Seng Hospital (TTSH)",
             "Alexandra Hospital",
             "Ang Mo Kio-Thye Hua Kwan Hospital Ltd",
             "Bright Vision Hospital",
             "Ng Teng Fong General Hospital & Jurong Community Hospital",
             "Kwong Wai Shiu Hospital And Nursing Home",
             "Ren Ci Long Term Care (Hougang)",
             "Ren Ci Community Hospital",
             "Ren Ci Nursing Home",
             "Sengkang General & Community Hospitals",
             "St Andrew's Community Hospital (SACH)",
             "St Luke's Hospital",
             "Yishun Community Hospital",
             "Adam Road Medical Centre",
             "Institute Of Mental Health (IMH)",
             "Johns Hopkins Singapore International Medical Centre (IMC)",
             "KK Women's And Children's Hospital (KKH)",
             "Mount Elizabeth Hospital",
             "National Cancer Centre Singapore (NCCS)",
             "National Dental Centre of Singapore (NDC)",
             "National Heart Centre Singapore (NHCS)",
             "National Neuroscience Institute (NNI)",
             "National Skin Centre (NSC)",
             "Singapore National Eye Centre (SNEC)",
             "Thomson Medical Centre (TMC)",
             ]

polyclinics = ["Ang Mo Kio Polyclinic (NHG)",
               "Bedok Polyclinic (Singhealth)",
               "Bukit Batok Polyclinic (NHG)",
               "Bukit Merah Polyclinic (Singhealth)",
               "Choa Chu Kang Polyclinic (NHG)",
               "Clementi Polyclinic (NHG)",
               "Geylang Polyclinic (Singhealth)",
               "Hougang Polyclinic (NHG)",
               "Jurong Polyclinic (NHG)",
               "Marine Parade Polyclinic (Singhealth)",
               "Outram Polyclinic (Singhealth)",
               "Pasir Ris Polyclinic (Singhealth)",
               "Queenstown Polyclinic (Singhealth)",
               "Sengkang Polyclinic (Singhealth)",
               "Tampines Polyclinic (Singhealth)",
               "Toa Payoh Polyclinic (NHG)",
               "Woodlands Polyclinic (NHG)",
               "Yishun Polyclinic (NHG)",
               ]

choices = polyclinics + hospitals
